import type { Agent, ScanResult } from "../types/agent.types";

const MOCK_NOW = 1_735_689_600_000;

export const mockAgents: Agent[] = [
  {
    id: "primary-maruqes",
    name: "maruqes",
    type: "primary",
    source: "global",
    sourcePath: "~/.config/opencode/opencode.jsonc",
    description: "Senior primary agent for code workflows.",
    model: "openai/gpt-5.5",
    effectiveModel: "openai/gpt-5.5",
    modelSource: "models.agent",
    permissionProfile: "autonomous_coder",
    mode: "primary",
    disabled: false,
    hidden: false,
    color: "primary",
    temperature: 0.2,
    topP: 0.9,
    steps: 40,
    commands: ["workmaruqes"],
    instructions: "Deliver simple, structured code with low duplication.",
    permissions: [
      { key: "filesystem.read", value: true, risk: "low" },
      { key: "filesystem.write", value: true, risk: "high" },
      { key: "bash", value: "safe", risk: "medium" },
    ],
    rawConfig: {},
    risk: "high",
    validationErrors: [],
    lastModified: MOCK_NOW,
  },
  {
    id: "subagent-reviewer",
    name: "reviewer",
    type: "subagent",
    source: "project",
    sourcePath: ".opencode/agents/reviewer.jsonc",
    description: "Strict reviewer focused on regressions and security.",
    model: "openai/gpt-5.5-mini",
    effectiveModel: "opencode-go/glm-5.2",
    modelSource: "models.agent",
    permissionProfile: "review_read_only",
    mode: "subagent",
    disabled: false,
    hidden: false,
    color: "warning",
    temperature: 0.1,
    steps: 20,
    commands: ["review"],
    instructions: "Find bugs, edge cases, risks, and duplication.",
    permissions: [{ key: "filesystem.read", value: true, risk: "low" }],
    rawConfig: {},
    risk: "low",
    validationErrors: [],
    lastModified: MOCK_NOW - 1000 * 60 * 30,
  },
  {
    id: "subagent-researcher",
    name: "researcher",
    type: "subagent",
    source: "global",
    sourcePath: "~/.config/opencode/agents/researcher.jsonc",
    description: "Research APIs, dependencies, and technical decisions.",
    model: "openai/gpt-5.5-mini",
    effectiveModel: "opencode-go/qwen3.7-plus",
    modelSource: "models.agent",
    permissionProfile: "research_read_only",
    mode: "subagent",
    disabled: false,
    hidden: false,
    color: "secondary",
    temperature: 0.1,
    steps: 18,
    commands: [],
    instructions: "Research local patterns before recommending libraries.",
    permissions: [
      { key: "filesystem.read", value: true, risk: "low" },
      { key: "network", value: "docs-only", risk: "medium" },
    ],
    rawConfig: {},
    risk: "medium",
    validationErrors: ["No domain limit configured for network."],
    lastModified: MOCK_NOW - 1000 * 60 * 60 * 2,
  },
];

export const mockScanResult: ScanResult = {
  agents: mockAgents,
  permissionProfiles: [
    {
      id: "autonomous-coder-profile",
      name: "autonomous_coder Profile",
      kind: "customProfile",
      source: "global",
      sourcePath: "~/.config/opencode/opencode.jsonc",
      rules: [
        { tool: "read", action: "allow", source: "autonomous_coder", risk: "low" },
        { tool: "edit", action: "allow", source: "autonomous_coder", risk: "high" },
        { tool: "task", action: "allow", source: "autonomous_coder", risk: "high" },
        { tool: "bash", pattern: "*", action: "ask", source: "autonomous_coder", risk: "high" },
        { tool: "bash", pattern: "npm test*", action: "allow", source: "autonomous_coder", risk: "high" },
      ],
      risk: "high",
      rawConfig: { read: "allow", edit: "allow", task: "allow", bash: { "*": "ask", "npm test*": "allow" } },
      validationErrors: [],
    },
    {
      id: "global-permission",
      name: "Global Permission",
      kind: "global",
      source: "global",
      sourcePath: "~/.config/opencode/opencode.jsonc",
      rules: [
        { tool: "edit", action: "ask", source: "Global Permission", risk: "high" },
        { tool: "bash", pattern: "*", action: "ask", source: "Global Permission", risk: "high" },
        { tool: "bash", pattern: "git *", action: "allow", source: "Global Permission", risk: "high" },
        { tool: "bash", pattern: "rm *", action: "deny", source: "Global Permission", risk: "low" },
      ],
      risk: "high",
      rawConfig: { edit: "ask", bash: { "*": "ask", "git *": "allow", "rm *": "deny" } },
      validationErrors: [],
    },
    {
      id: "reviewer-effective",
      name: "reviewer Effective",
      kind: "effective",
      agentId: "subagent-reviewer",
      source: "project",
      sourcePath: ".opencode/agents/reviewer.md",
      rules: [
        { tool: "edit", action: "deny", source: "reviewer Effective", risk: "low" },
        { tool: "bash", action: "deny", source: "reviewer Effective", risk: "low" },
        { tool: "webfetch", action: "allow", source: "reviewer Effective", risk: "medium" },
      ],
      risk: "medium",
      rawConfig: { edit: "deny", bash: "deny", webfetch: "allow" },
      validationErrors: [],
    },
  ],
  instructionSources: [
    {
      id: "global-instructions",
      kind: "configInstructions",
      source: "global",
      sourcePath: "~/.config/opencode/opencode.jsonc",
      label: "CONTRIBUTING.md",
      reference: "CONTRIBUTING.md",
      validationErrors: [],
    },
    {
      id: "reviewer-prompt",
      kind: "markdownAgentBody",
      agentId: "subagent-reviewer",
      source: "project",
      sourcePath: ".opencode/agents/reviewer.md",
      label: "reviewer markdown body",
      content: "You are in code review mode. Focus on bugs, regressions, security, and maintainability.",
      validationErrors: [],
    },
  ],
  configFiles: [
    {
      id: "global-config",
      source: "global",
      path: "~/.config/opencode/opencode.jsonc",
      kind: "jsonc",
      rawConfig: { permission: { edit: "ask", bash: { "*": "ask" } } },
      agentsCount: 1,
      permissionProfilesCount: 1,
      instructionSourcesCount: 1,
      validationErrors: [],
      lastModified: MOCK_NOW,
    },
  ],
};
